#!/bin/bash

# Sales Dashboard - Appwrite Setup Script
# This script automates the setup of your Appwrite database using the CLI

set -e

echo "🚀 Sales Dashboard - Appwrite Setup"
echo "===================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Appwrite CLI is installed
if ! command -v appwrite &> /dev/null; then
    echo -e "${RED}Error: Appwrite CLI is not installed.${NC}"
    echo "Install it with: npm install -g appwrite-cli"
    exit 1
fi

echo -e "${GREEN}✓ Appwrite CLI detected${NC}"
echo ""

# Step 1: Check Appwrite login status
echo "Step 1: Check Appwrite Login"
echo "----------------------------"
echo ""

# Check if already logged in
if appwrite account get &> /dev/null; then
    echo -e "${GREEN}✓ Already logged in to Appwrite${NC}"
else
    echo "You'll be redirected to your browser to authenticate..."
    echo ""
    appwrite login
    echo ""
    echo -e "${GREEN}✓ Successfully logged in${NC}"
fi
echo ""

# Step 2: Initialize project
echo "Step 2: Initialize Appwrite Project"
echo "------------------------------------"
echo ""

# Check if already initialized
if [ ! -f "appwrite.json" ]; then
    appwrite init project
else
    echo -e "${YELLOW}Project already initialized. Skipping...${NC}"
fi

echo ""
echo -e "${GREEN}✓ Project initialized${NC}"
echo ""

# Get project ID from appwrite.json
PROJECT_ID=$(grep -o '"projectId": "[^"]*"' appwrite.json | cut -d'"' -f4)

if [ -z "$PROJECT_ID" ]; then
    echo -e "${RED}Error: Could not find project ID${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Project ID: ${PROJECT_ID}${NC}"
echo ""

# Step 3: Update appwrite.json with project ID
echo "Step 3: Configure Database Schema"
echo "----------------------------------"
echo ""

# Update appwrite.json with the project ID
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sed -i '' "s/\"projectId\": \"\"/\"projectId\": \"$PROJECT_ID\"/" appwrite.json
else
    # Linux
    sed -i "s/\"projectId\": \"\"/\"projectId\": \"$PROJECT_ID\"/" appwrite.json
fi

echo -e "${GREEN}✓ Updated appwrite.json with project ID${NC}"
echo ""

# Step 4: Deploy database structure
echo "Step 4: Deploy Database & Collections"
echo "--------------------------------------"
echo "This will create:"
echo "  - 1 database (SalesDashboard)"
echo "  - 5 collections (stores, kpis, sales_data, reports, snapshots)"
echo ""

appwrite push databases

echo ""
echo -e "${GREEN}✓ Database and collections deployed successfully!${NC}"
echo ""

# Step 5: Create API Key
echo "Step 5: Create API Key"
echo "----------------------"
echo ""
echo "Creating an API key with database read/write permissions..."
echo ""

# Create API key with the necessary scopes
API_KEY_NAME="Sales Dashboard Server - $(date +%Y%m%d)"
API_KEY_RESULT=$(appwrite projects create-key \
    --project-id "$PROJECT_ID" \
    --name "$API_KEY_NAME" \
    --scopes "databases.read" "databases.write")

# Extract the API key from the result
API_KEY=$(echo "$API_KEY_RESULT" | grep -o '"secret":"[^"]*' | cut -d'"' -f4)

echo ""
echo -e "${GREEN}✓ API Key created successfully${NC}"
echo ""

# Step 6: Create .env.local file
echo "Step 6: Generate Environment Variables"
echo "---------------------------------------"
echo ""

# Database and Collection IDs
DATABASE_ID="sales-dashboard-db"
STORES_COLLECTION_ID="stores"
KPIS_COLLECTION_ID="kpis"
SALES_COLLECTION_ID="sales_data"
REPORTS_COLLECTION_ID="reports"
SNAPSHOTS_COLLECTION_ID="snapshots"

# Get the endpoint from CLI config
ENDPOINT="https://cloud.appwrite.io/v1"

# Create .env.local file
cat > .env.local << EOF
# Appwrite Configuration
# Auto-generated by setup-appwrite.sh on $(date)

# Server-side (API Key required)
APPWRITE_ENDPOINT=$ENDPOINT
APPWRITE_PROJECT_ID=$PROJECT_ID
APPWRITE_API_KEY=$API_KEY

# Client-side (Public keys)
NEXT_PUBLIC_APPWRITE_ENDPOINT=$ENDPOINT
NEXT_PUBLIC_APPWRITE_PROJECT_ID=$PROJECT_ID

# Database and Collection IDs
APPWRITE_DATABASE_ID=$DATABASE_ID
APPWRITE_COLLECTION_STORES_ID=$STORES_COLLECTION_ID
APPWRITE_COLLECTION_KPIS_ID=$KPIS_COLLECTION_ID
APPWRITE_COLLECTION_SALES_ID=$SALES_COLLECTION_ID
APPWRITE_COLLECTION_REPORTS_ID=$REPORTS_COLLECTION_ID
APPWRITE_COLLECTION_SNAPSHOTS_ID=$SNAPSHOTS_COLLECTION_ID

NEXT_PUBLIC_APPWRITE_DATABASE_ID=$DATABASE_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_STORES_ID=$STORES_COLLECTION_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_KPIS_ID=$KPIS_COLLECTION_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_SALES_ID=$SALES_COLLECTION_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_REPORTS_ID=$REPORTS_COLLECTION_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_SNAPSHOTS_ID=$SNAPSHOTS_COLLECTION_ID

# Vercel Blob (optional, for PDF storage)
# BLOB_READ_WRITE_TOKEN=your_vercel_blob_token_here
EOF

echo -e "${GREEN}✓ Created .env.local with all configuration${NC}"
echo ""

# Summary
echo ""
echo "=========================================="
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Your Appwrite database is ready to use!"
echo ""
echo "Project Details:"
echo "  • Project ID: $PROJECT_ID"
echo "  • Database: SalesDashboard ($DATABASE_ID)"
echo "  • Endpoint: $ENDPOINT"
echo ""
echo "Collections created:"
echo "  ✓ stores"
echo "  ✓ kpis"
echo "  ✓ sales_data (with unique index)"
echo "  ✓ reports"
echo "  ✓ snapshots"
echo ""
echo "Next steps:"
echo "  1. Run: npm run dev"
echo "  2. Open: http://localhost:3000"
echo "  3. Start adding stores and KPIs!"
echo ""
echo "⚠️  Important: Your API key is stored in .env.local"
echo "    Keep this file secure and never commit it to git!"
echo ""
echo "📚 View your project: https://cloud.appwrite.io/console/project-$PROJECT_ID"
echo ""
